/*

 FLOORMAP_FULL_SEGMENTS.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 150 x 18
   Tile set      : C:\Users\andy_000\Documents\GameBoyTools\gbtd22\Sprites\jumpy_floor.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : Yes
   Block size    : 18

 This file was generated by GBMB v1.8

*/

#define floormap_full_segmentsWidth 150
#define floormap_full_segmentsHeight 18
#define floormap_full_segmentsBank 0

extern unsigned char floormap_full_segmentsBLK0[];
extern unsigned char floormap_full_segmentsBLK1[];
extern unsigned char floormap_full_segmentsBLK2[];
extern unsigned char floormap_full_segmentsBLK3[];
extern unsigned char floormap_full_segmentsBLK4[];
extern unsigned char floormap_full_segmentsBLK5[];
extern unsigned char floormap_full_segmentsBLK6[];
extern unsigned char floormap_full_segmentsBLK7[];
extern unsigned char floormap_full_segmentsBLK8[];
extern unsigned char floormap_full_segmentsBLK9[];
extern unsigned char floormap_full_segmentsBLK10[];
extern unsigned char floormap_full_segmentsBLK11[];
extern unsigned char floormap_full_segmentsBLK12[];
extern unsigned char floormap_full_segmentsBLK13[];
extern unsigned char floormap_full_segmentsBLK14[];
extern unsigned char floormap_full_segmentsBLK15[];
extern unsigned char floormap_full_segmentsBLK16[];
extern unsigned char floormap_full_segmentsBLK17[];
extern unsigned char floormap_full_segmentsBLK18[];
extern unsigned char floormap_full_segmentsBLK19[];
extern unsigned char floormap_full_segmentsBLK20[];
extern unsigned char floormap_full_segmentsBLK21[];
extern unsigned char floormap_full_segmentsBLK22[];
extern unsigned char floormap_full_segmentsBLK23[];
extern unsigned char floormap_full_segmentsBLK24[];
extern unsigned char floormap_full_segmentsBLK25[];
extern unsigned char floormap_full_segmentsBLK26[];
extern unsigned char floormap_full_segmentsBLK27[];
extern unsigned char floormap_full_segmentsBLK28[];
extern unsigned char floormap_full_segmentsBLK29[];
extern unsigned char floormap_full_segmentsBLK30[];
extern unsigned char floormap_full_segmentsBLK31[];
extern unsigned char floormap_full_segmentsBLK32[];
extern unsigned char floormap_full_segmentsBLK33[];
extern unsigned char floormap_full_segmentsBLK34[];
extern unsigned char floormap_full_segmentsBLK35[];
extern unsigned char floormap_full_segmentsBLK36[];
extern unsigned char floormap_full_segmentsBLK37[];
extern unsigned char floormap_full_segmentsBLK38[];
extern unsigned char floormap_full_segmentsBLK39[];
extern unsigned char floormap_full_segmentsBLK40[];
extern unsigned char floormap_full_segmentsBLK41[];
extern unsigned char floormap_full_segmentsBLK42[];
extern unsigned char floormap_full_segmentsBLK43[];
extern unsigned char floormap_full_segmentsBLK44[];
extern unsigned char floormap_full_segmentsBLK45[];
extern unsigned char floormap_full_segmentsBLK46[];
extern unsigned char floormap_full_segmentsBLK47[];
extern unsigned char floormap_full_segmentsBLK48[];
extern unsigned char floormap_full_segmentsBLK49[];
extern unsigned char floormap_full_segmentsBLK50[];
extern unsigned char floormap_full_segmentsBLK51[];
extern unsigned char floormap_full_segmentsBLK52[];
extern unsigned char floormap_full_segmentsBLK53[];
extern unsigned char floormap_full_segmentsBLK54[];
extern unsigned char floormap_full_segmentsBLK55[];
extern unsigned char floormap_full_segmentsBLK56[];
extern unsigned char floormap_full_segmentsBLK57[];
extern unsigned char floormap_full_segmentsBLK58[];
extern unsigned char floormap_full_segmentsBLK59[];
extern unsigned char floormap_full_segmentsBLK60[];
extern unsigned char floormap_full_segmentsBLK61[];
extern unsigned char floormap_full_segmentsBLK62[];
extern unsigned char floormap_full_segmentsBLK63[];
extern unsigned char floormap_full_segmentsBLK64[];
extern unsigned char floormap_full_segmentsBLK65[];
extern unsigned char floormap_full_segmentsBLK66[];
extern unsigned char floormap_full_segmentsBLK67[];
extern unsigned char floormap_full_segmentsBLK68[];
extern unsigned char floormap_full_segmentsBLK69[];
extern unsigned char floormap_full_segmentsBLK70[];
extern unsigned char floormap_full_segmentsBLK71[];
extern unsigned char floormap_full_segmentsBLK72[];
extern unsigned char floormap_full_segmentsBLK73[];
extern unsigned char floormap_full_segmentsBLK74[];
extern unsigned char floormap_full_segmentsBLK75[];
extern unsigned char floormap_full_segmentsBLK76[];
extern unsigned char floormap_full_segmentsBLK77[];
extern unsigned char floormap_full_segmentsBLK78[];
extern unsigned char floormap_full_segmentsBLK79[];
extern unsigned char floormap_full_segmentsBLK80[];
extern unsigned char floormap_full_segmentsBLK81[];
extern unsigned char floormap_full_segmentsBLK82[];
extern unsigned char floormap_full_segmentsBLK83[];
extern unsigned char floormap_full_segmentsBLK84[];
extern unsigned char floormap_full_segmentsBLK85[];
extern unsigned char floormap_full_segmentsBLK86[];
extern unsigned char floormap_full_segmentsBLK87[];
extern unsigned char floormap_full_segmentsBLK88[];
extern unsigned char floormap_full_segmentsBLK89[];
extern unsigned char floormap_full_segmentsBLK90[];
extern unsigned char floormap_full_segmentsBLK91[];
extern unsigned char floormap_full_segmentsBLK92[];
extern unsigned char floormap_full_segmentsBLK93[];
extern unsigned char floormap_full_segmentsBLK94[];
extern unsigned char floormap_full_segmentsBLK95[];
extern unsigned char floormap_full_segmentsBLK96[];
extern unsigned char floormap_full_segmentsBLK97[];
extern unsigned char floormap_full_segmentsBLK98[];
extern unsigned char floormap_full_segmentsBLK99[];
extern unsigned char floormap_full_segmentsBLK100[];
extern unsigned char floormap_full_segmentsBLK101[];
extern unsigned char floormap_full_segmentsBLK102[];
extern unsigned char floormap_full_segmentsBLK103[];
extern unsigned char floormap_full_segmentsBLK104[];
extern unsigned char floormap_full_segmentsBLK105[];
extern unsigned char floormap_full_segmentsBLK106[];
extern unsigned char floormap_full_segmentsBLK107[];
extern unsigned char floormap_full_segmentsBLK108[];
extern unsigned char floormap_full_segmentsBLK109[];
extern unsigned char floormap_full_segmentsBLK110[];
extern unsigned char floormap_full_segmentsBLK111[];
extern unsigned char floormap_full_segmentsBLK112[];
extern unsigned char floormap_full_segmentsBLK113[];
extern unsigned char floormap_full_segmentsBLK114[];
extern unsigned char floormap_full_segmentsBLK115[];
extern unsigned char floormap_full_segmentsBLK116[];
extern unsigned char floormap_full_segmentsBLK117[];
extern unsigned char floormap_full_segmentsBLK118[];
extern unsigned char floormap_full_segmentsBLK119[];
extern unsigned char floormap_full_segmentsBLK120[];
extern unsigned char floormap_full_segmentsBLK121[];
extern unsigned char floormap_full_segmentsBLK122[];
extern unsigned char floormap_full_segmentsBLK123[];
extern unsigned char floormap_full_segmentsBLK124[];
extern unsigned char floormap_full_segmentsBLK125[];
extern unsigned char floormap_full_segmentsBLK126[];
extern unsigned char floormap_full_segmentsBLK127[];
extern unsigned char floormap_full_segmentsBLK128[];
extern unsigned char floormap_full_segmentsBLK129[];
extern unsigned char floormap_full_segmentsBLK130[];
extern unsigned char floormap_full_segmentsBLK131[];
extern unsigned char floormap_full_segmentsBLK132[];
extern unsigned char floormap_full_segmentsBLK133[];
extern unsigned char floormap_full_segmentsBLK134[];
extern unsigned char floormap_full_segmentsBLK135[];
extern unsigned char floormap_full_segmentsBLK136[];
extern unsigned char floormap_full_segmentsBLK137[];
extern unsigned char floormap_full_segmentsBLK138[];
extern unsigned char floormap_full_segmentsBLK139[];
extern unsigned char floormap_full_segmentsBLK140[];
extern unsigned char floormap_full_segmentsBLK141[];
extern unsigned char floormap_full_segmentsBLK142[];
extern unsigned char floormap_full_segmentsBLK143[];
extern unsigned char floormap_full_segmentsBLK144[];
extern unsigned char floormap_full_segmentsBLK145[];
extern unsigned char floormap_full_segmentsBLK146[];
extern unsigned char floormap_full_segmentsBLK147[];
extern unsigned char floormap_full_segmentsBLK148[];
extern unsigned char floormap_full_segmentsBLK149[];

/* End of FLOORMAP_FULL_SEGMENTS.H */
