/*

 FLOORMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 150 x 18
   Tile set      : C:\Users\andy_000\Documents\GameBoyTools\gbtd22\Sprites\jumpy_floor.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define floormap_fullWidth 150
#define floormap_fullHeight 18
#define floormap_fullBank 0

extern unsigned char floormap_full[];

/* End of FLOORMAP.H */
